from typing import Final

CONVERSION_COEFFS: Final[dict[str, float]] = {
    "USD": 1.0000,
    "EUR": 1.1500,
    "GBP": 1.3500,
    "CAD": 0.7300,
    "PLN": 0.2700,
    "MXN": 0.0560,
    "UAH": 0.0240,
}

COUNTRY_CURRENCIES: Final[dict[str, str]] = {
    "DEU": "EUR",
    "CAN": "CAD",
    "USA": "USD",
    "FRA": "EUR",
    "UKR": "UAH",
    "POL": "PLN",
    "MEX": "MXN",
    "GBR": "GBP",
}

ERROR_CATEGORIES: Final[dict[str, str]] = {
    "0.01": "General decline",
    "0.02": "General decline",
    "0.03": "General decline",
    "0.04": "General decline",
    "1.01": "Service access",
    "1.02": "Service access",
    "2.01": "Validation errors",
    "2.02": "Validation errors",
    "2.03": "Validation errors",
    "2.04": "Validation errors",
    "2.05": "Validation errors",
    "2.06": "Validation errors",
    "2.07": "Validation errors",
    "2.08": "Validation errors",
    "2.09": "Validation errors",
    "2.10": "Validation errors",
    "2.11": "Validation errors",
    "2.12": "Validation errors",
    "2.13": "Validation errors",
    "2.14": "Validation errors",
    "2.15": "Validation errors",
    "2.16": "Validation errors",
    "2.17": "Validation errors",
    "2.18": "Validation errors",
    "3.01": "Transaction declines",
    "3.02": "Transaction declines",
    "3.03": "Transaction declines",
    "3.04": "Transaction declines",
    "3.05": "Transaction declines",
    "3.06": "Transaction declines",
    "3.07": "Transaction declines",
    "3.08": "Transaction declines",
    "3.09": "Transaction declines",
    "3.10": "Transaction declines",
    "3.1": "Transaction declines",
    "3.11": "Transaction declines",
    "3.12": "Transaction declines",
    "3.13": "Transaction declines",
    "4.01": "Fraud and anti-fraud",
    "4.02": "Fraud and anti-fraud",
    "4.05": "Fraud and anti-fraud",
    "4.07": "Fraud and anti-fraud",
    "4.09": "Fraud and anti-fraud",
    "4.03": "Card blocked or restricted",
    "4.04": "Card blocked or restricted",
    "4.08": "Data or card verification",
    "5.01": "Data or card verification",
    "5.02": "Data or card verification",
    "7.01": "Data or card verification",
    "5.03": "Connection or processing issues",
    "5.08": "Connection or processing issues",
    "6.01": "Connection or processing issues",
    "6.02": "Connection or processing issues",
    "6.03": "Connection or processing issues",
    "5.04": "Merchant configuration or activation errors",
    "5.05": "Merchant configuration or activation errors",
    "5.09": "Merchant configuration or activation errors",
    "5.10": "Merchant configuration or activation errors",
    "5.12": "Merchant configuration or activation errors",
    "4.06": "Restrictions or duplicate transactions",
    "5.06": "Restrictions or duplicate transactions",
    "5.07": "Restrictions or duplicate transactions",
    "5.11": "Restrictions or duplicate transactions",
    "7.02": "Payment system errors",
    "7.03": "Payment system errors",
    "7.04": "Payment system errors",
    "7.05": "Payment system errors",
    "7.06": "Payment system errors",
    "7.07": "Payment system errors",
    "no_error": "No error",
}
